// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PresentationYandexMusic.Areas.Admin.Controllers
{
    public partial class AdminSingerController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminSingerController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult EditSinger()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.EditSinger);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteSinger()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteSinger);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult GetSingerImage()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.GetSingerImage);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminSingerController Actions { get { return MVC.Admin.AdminSinger; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AdminSinger";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AdminSinger";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string CreateSinger = "CreateSinger";
            public readonly string FormSingerSuccess = "FormSingerSuccess";
            public readonly string EditSinger = "EditSinger";
            public readonly string DeleteSinger = "DeleteSinger";
            public readonly string GetSingerImage = "GetSingerImage";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string CreateSinger = "CreateSinger";
            public const string FormSingerSuccess = "FormSingerSuccess";
            public const string EditSinger = "EditSinger";
            public const string DeleteSinger = "DeleteSinger";
            public const string GetSingerImage = "GetSingerImage";
        }


        static readonly ActionParamsClass_CreateSinger s_params_CreateSinger = new ActionParamsClass_CreateSinger();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateSinger CreateSingerParams { get { return s_params_CreateSinger; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateSinger
        {
            public readonly string singerModel = "singerModel";
        }
        static readonly ActionParamsClass_EditSinger s_params_EditSinger = new ActionParamsClass_EditSinger();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditSinger EditSingerParams { get { return s_params_EditSinger; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditSinger
        {
            public readonly string id = "id";
            public readonly string singerView = "singerView";
        }
        static readonly ActionParamsClass_DeleteSinger s_params_DeleteSinger = new ActionParamsClass_DeleteSinger();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteSinger DeleteSingerParams { get { return s_params_DeleteSinger; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteSinger
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetSingerImage s_params_GetSingerImage = new ActionParamsClass_GetSingerImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSingerImage GetSingerImageParams { get { return s_params_GetSingerImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSingerImage
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CreateSinger = "CreateSinger";
                public readonly string DeleteSinger = "DeleteSinger";
                public readonly string EditSinger = "EditSinger";
                public readonly string FormCreateSinger = "FormCreateSinger";
                public readonly string FormEditSinger = "FormEditSinger";
                public readonly string FormSingerSuccess = "FormSingerSuccess";
            }
            public readonly string CreateSinger = "~/Areas/Admin/Views/AdminSinger/CreateSinger.cshtml";
            public readonly string DeleteSinger = "~/Areas/Admin/Views/AdminSinger/DeleteSinger.cshtml";
            public readonly string EditSinger = "~/Areas/Admin/Views/AdminSinger/EditSinger.cshtml";
            public readonly string FormCreateSinger = "~/Areas/Admin/Views/AdminSinger/FormCreateSinger.cshtml";
            public readonly string FormEditSinger = "~/Areas/Admin/Views/AdminSinger/FormEditSinger.cshtml";
            public readonly string FormSingerSuccess = "~/Areas/Admin/Views/AdminSinger/FormSingerSuccess.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AdminSingerController : PresentationYandexMusic.Areas.Admin.Controllers.AdminSingerController
    {
        public T4MVC_AdminSingerController() : base(Dummy.Instance) { }

        [NonAction]
        partial void CreateSingerOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult CreateSinger()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateSinger);
            CreateSingerOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateSingerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PresentationYandexMusic.Areas.Admin.ViewModel.Singer.CreateSingerViewModel singerModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateSinger(PresentationYandexMusic.Areas.Admin.ViewModel.Singer.CreateSingerViewModel singerModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateSinger);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "singerModel", singerModel);
            CreateSingerOverride(callInfo, singerModel);
            return callInfo;
        }

        [NonAction]
        partial void FormSingerSuccessOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult FormSingerSuccess()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.FormSingerSuccess);
            FormSingerSuccessOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditSingerOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ViewResult EditSinger(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.EditSinger);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditSingerOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditSingerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PresentationYandexMusic.Areas.Admin.ViewModel.Singer.EditSingerViewModel singerView);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditSinger(PresentationYandexMusic.Areas.Admin.ViewModel.Singer.EditSingerViewModel singerView)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditSinger);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "singerView", singerView);
            EditSingerOverride(callInfo, singerView);
            return callInfo;
        }

        [NonAction]
        partial void DeleteSingerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteSinger(int? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteSinger);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteSingerOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteSingerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteSinger(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteSinger);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteSingerOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GetSingerImageOverride(T4MVC_System_Web_Mvc_FileResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.FileResult GetSingerImage(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.GetSingerImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetSingerImageOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
