// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PresentationYandexMusic.Areas.Admin.Controllers
{
    public partial class AdminTrackController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminTrackController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult EditTrack()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.EditTrack);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteTrack()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteTrack);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult GetTrackImage()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.GetTrackImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ReplaceItem()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ReplaceItem);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminTrackController Actions { get { return MVC.Admin.AdminTrack; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AdminTrack";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AdminTrack";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string CreateTrack = "CreateTrack";
            public readonly string EditTrack = "EditTrack";
            public readonly string DeleteTrack = "DeleteTrack";
            public readonly string GetTrackImage = "GetTrackImage";
            public readonly string ReplaceItem = "ReplaceItem";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string CreateTrack = "CreateTrack";
            public const string EditTrack = "EditTrack";
            public const string DeleteTrack = "DeleteTrack";
            public const string GetTrackImage = "GetTrackImage";
            public const string ReplaceItem = "ReplaceItem";
        }


        static readonly ActionParamsClass_CreateTrack s_params_CreateTrack = new ActionParamsClass_CreateTrack();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateTrack CreateTrackParams { get { return s_params_CreateTrack; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateTrack
        {
            public readonly string trackModel = "trackModel";
        }
        static readonly ActionParamsClass_EditTrack s_params_EditTrack = new ActionParamsClass_EditTrack();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditTrack EditTrackParams { get { return s_params_EditTrack; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditTrack
        {
            public readonly string id = "id";
            public readonly string trackView = "trackView";
        }
        static readonly ActionParamsClass_DeleteTrack s_params_DeleteTrack = new ActionParamsClass_DeleteTrack();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteTrack DeleteTrackParams { get { return s_params_DeleteTrack; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteTrack
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetTrackImage s_params_GetTrackImage = new ActionParamsClass_GetTrackImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetTrackImage GetTrackImageParams { get { return s_params_GetTrackImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetTrackImage
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ReplaceItem s_params_ReplaceItem = new ActionParamsClass_ReplaceItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReplaceItem ReplaceItemParams { get { return s_params_ReplaceItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReplaceItem
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CreateTrack = "CreateTrack";
                public readonly string DeleteTrack = "DeleteTrack";
                public readonly string EditTrack = "EditTrack";
            }
            public readonly string CreateTrack = "~/Areas/Admin/Views/AdminTrack/CreateTrack.cshtml";
            public readonly string DeleteTrack = "~/Areas/Admin/Views/AdminTrack/DeleteTrack.cshtml";
            public readonly string EditTrack = "~/Areas/Admin/Views/AdminTrack/EditTrack.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AdminTrackController : PresentationYandexMusic.Areas.Admin.Controllers.AdminTrackController
    {
        public T4MVC_AdminTrackController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateTrackOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult CreateTrack()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.CreateTrack);
            CreateTrackOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateTrackOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PresentationYandexMusic.Areas.Admin.ViewModel.Track.CreateTrackViewModel trackModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateTrack(PresentationYandexMusic.Areas.Admin.ViewModel.Track.CreateTrackViewModel trackModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateTrack);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "trackModel", trackModel);
            CreateTrackOverride(callInfo, trackModel);
            return callInfo;
        }

        [NonAction]
        partial void EditTrackOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ViewResult EditTrack(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.EditTrack);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditTrackOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditTrackOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PresentationYandexMusic.Areas.Admin.ViewModel.Track.EditTrackViewModel trackView);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditTrack(PresentationYandexMusic.Areas.Admin.ViewModel.Track.EditTrackViewModel trackView)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditTrack);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "trackView", trackView);
            EditTrackOverride(callInfo, trackView);
            return callInfo;
        }

        [NonAction]
        partial void DeleteTrackOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteTrack(int? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteTrack);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteTrackOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteTrackOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteTrack(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteTrack);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteTrackOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GetTrackImageOverride(T4MVC_System_Web_Mvc_FileResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.FileResult GetTrackImage(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.GetTrackImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetTrackImageOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ReplaceItemOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult ReplaceItem(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ReplaceItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ReplaceItemOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
